.github/workflows/docker-rollups.yml
README.md
yarn.lock

Changes to streamline rollups docker image generation. I also include a `release` with information about the current strategy, including the new one for rollups docker image publishing. More details are below.
**What is published to`ghcr.io`:**
* For pull requests that change `rollups` or any `packages` will trigger the GA that publishes an image of your code tagged as pr-<number>
* For push events to the `main` branch changes `rollups` and/or any `packages` it will publish an image tagged as `edge`. That is a common tag that means access to fresh features, but it may be unstable. 
* Push event from a tag named e.g. `rollups@a.b.c` the image will be generated tagged as the version `a.b.c` and also tag `latest`
**What is published to `docker.io`**
* Push event from a tag named e.g. …

Chore: Update GA for rollups docker image publishing

---

packages/wallet/__tests__/useOnboard.test.tsx
packages/wallet/src/useOnboard.tsx

This PR adds more unit tests for `packages/wallet` with the goal to increase the test coverage to about `75%`.

#9 Improve test coverage for packages/wallet

---

packages/ui/__tests__/components/Address.test.tsx
packages/ui/__tests__/components/AddressText.test.tsx
packages/ui/__tests__/components/Banner.test.tsx
packages/ui/__tests__/components/BigNumberText.test.tsx
packages/ui/__tests__/components/Card.test.tsx
packages/ui/__tests__/components/Footer.test.tsx
packages/ui/__tests__/components/Layout.test.tsx
packages/ui/__tests__/components/Notification.test.tsx
packages/ui/__tests__/components/header/ConnectWallet.test.tsx
packages/ui/__tests__/components/header/NavBar.test.tsx
packages/ui/__tests__/components/header/modals/WalletMobileModal.test.tsx
packages/ui/src/components/Footer.tsx

Optimized speed of unit tests for `packages/ui` by refactoring imports.
Before the changes:
After the changes:

#16 Optimize unit tests for packages/ui

---

apps/rollups/__tests__/components/Web3Container.test.tsx
apps/rollups/__tests__/containers/rollups/DApp.test.tsx
apps/rollups/__tests__/services/useRollupsFactory.test.tsx
apps/rollups/__tests__/services/useRollupsGraphQL.test.tsx
apps/rollups/src/services/useRollupsGraphQL.tsx

Optimizing the unit test on the `apps/rollups`
Before the changes, there are some warning on the `graphql` endpoint. Time to complete **~18s**
After the changes
Fixes #17

#17 Optimize Unit Test for apps/rollups

---

.github/workflows/docker-rollups.yml
docker/docker-bake.rollups.hcl

Changes applied to the GitHub action that generates docker images for the Rollup Explorer app. 
1. Added integration with Depot. 
2. Add permission for issuing OIDC tokens for the workflow run.
3. Removed QEMU setup step
4. Removed docker/build-push-action step 
5. **Added a docker-bake.hcl to describe a high-level build command.**
6. Also, added a bake-override in the workflow definition to avoid problems with working directory.

Replacing QEMU with Depot

---

CHANGELOG.md
apps/staking/__tests__/contexts/ga4Tracker.test.tsx
apps/staking/src/contexts/ga4Tracker.tsx

A report was made that links in the headers were changing the address bar, but the app would not "display" the page itself. But the reality is that the links and buttons (usually calling the next router programmatically) would also not work. After checking the released tags, the problem was introduced on [v3.5.0](https://github.com/cartesi/explorer/releases/tag/v3.5.0) after checking the [changes between the tags](https://github.com/cartesi/explorer/compare/v3.4.0...v3.5.0?diff=unified), the cause was an item added in the `useEffect` watchlist causing an infinite loop in two `useEffect` hooks inside the ga4Tracker.tsx [here](https://github.com/cartesi/explorer/blob/32f43b7f0ad80283d2b8fbd4777571959ba2cb4e/apps/staking/src/contexts/ga4Tracker.tsx#L63) and …

Fix: App navigation

---

apps/rollups/__tests__/containers/rollups/DApp.test.tsx
apps/rollups/src/containers/rollups/DApp.tsx

Added no inputs label. 
Before:
After:

#49 Add no inputs label

---

apps/staking/.storybook/ColorMode.tsx
apps/staking/.storybook/main.js
apps/staking/.storybook/preview.tsx
packages/ui/.storybook/main.js

Fix for staking storybook. The issue was due to custom hooks being invoked in storybook decorator, which after recent upgrade doesn't work anymore.
I also fixed the storybook `packages/ui` build, that was failing due to not transpiled library.
There is another runtime issue I noticed for `packages/ui`'s storybook:
```
Uncaught Error: WalletConnect requires a projectId. Please visit https://cloud.walletconnect.com to get one.
```
Probably a wallet provider is missing in the storybook preview, but I haven't checked this further.

#75 Fix storybooks

---

apps/staking/src/components/BlocksChart.tsx
apps/staking/src/components/PageHeader.tsx
apps/staking/src/components/SearchInput.tsx
apps/staking/src/components/block/BlockCard.tsx
apps/staking/src/pages/blocks/[[...block]].tsx
packages/ui/src/styles/foundations/colors.ts

Uses as base branch `feature/57-update-stake-page-ui` ([PR](https://github.com/cartesi/explorer/pull/80)).
This is how the blocks page looks after the changes:
https://github.com/cartesi/explorer/assets/6005179/56ba783d-5629-4402-9006-b0e1727d431e

#60 Update blocks page UI

---

CHANGELOG.md
apps/staking/src/components/Layout.tsx

Some of the footer links were pointing to old content or content that was not available anymore. This PR covers this by updating some of the links to the newer content and others to the new location.

chore:  Update footer links to navigate to functional content.

---

apps/staking/__tests__/graphql/hooks/useBlocks.test.tsx
apps/staking/__tests__/graphql/useStakingPools.test.tsx
apps/staking/src/graphql/hooks/useBlocks.ts
apps/staking/src/graphql/hooks/useNodes.ts
apps/staking/src/graphql/hooks/usePoolActivities.ts
apps/staking/src/graphql/hooks/usePoolBalances.ts
apps/staking/src/graphql/hooks/useStakingPool.ts
apps/staking/src/graphql/hooks/useStakingPoolFeeHistories.ts
apps/staking/src/graphql/hooks/useStakingPoolPerformance.ts
apps/staking/src/graphql/hooks/useStakingPoolUserHistories.ts
apps/staking/src/graphql/hooks/useStakingPools.ts
apps/staking/src/graphql/hooks/useSummary.ts
apps/staking/src/graphql/hooks/useTotalPoolBalance.ts
apps/staking/src/graphql/hooks/useUser.ts
apps/staking/src/graphql/hooks/useUsers.ts

I removed the `pollInterval` setting for all graphql queries so that we are doing any http requests to the graphql BE only on page load. This can be easily noticed on the `/blocks` page, where we were previously polling a lot of data every 30 seconds.
I also checked the `useBlockNumber` custom hook that we have in `/staking/src/services/eth.tsx`. It is used on most of the pages and although it often causes re-renders in components that use it (because the block number changes every ~15 seconds), I didn't notice it causing any side effects like extra http requests happening. That's why I didn't make any changes in `useBlockNumber`.
1. Build the app locally for dev env
2. Go to the `/` (home), or `/blocks` , or any other page where we were previously polling the graphql queries
3. Observe …

#156 Disable query polling

---

apps/staking/src/components/stake/PoolSetting.tsx

Small fix for the settings layout on the `/pools/{address}/manage` page.
1. Connect your wallet.
2. Click the link node-runners in the header.
3. Click manage icon in a pool. PS: Create one if necessary.
4. Scroll down to the settings area.
5. You should be able to see the misaligned fields according to the screenshot.

#168 Fix layout for pool settings

---

apps/staking/src/components/SearchInput.tsx
apps/staking/src/pages/blocks/[[...block]].tsx

I made the following tweaks:
- Fixed the text color of the search in light mode
- Change the placeholder text to `Search by producer`
- Added a debounce to the search

#171 Tweaks for blocks search

---

CHANGELOG.md
packages/services/src/ens.tsx
packages/ui/src/components/Address.tsx

Code changes are needed to add options to the `useENS` hook to control when to fetch or not fetch ENS information in some parts of the UI (It affects mainly when local-cache misses happen), i.e. no network calls. The **second** change is just an amendment to the Changelog release date.

Feat: Add Opts for useEns hook

---

CHANGELOG.md
apps/staking/src/pages/api/cron/ens-update-stale.ts

Code changes to increase the duration time on the function level. Only the API function handling the update of stale ENS entries will have a duration above the default 15 seconds on Vercel. 
The reason is that, looking at the logs, the call for the ENS graphQL takes a considerable portion of that duration limit 
varying between 7 ~ 11 s, plus the duration of avatar text checks **on-chain** may take around 4s ~ 6s passing the limit of 15s. 
These times are based on the current 742 entries marked as stale and needed to be checked. The graphQL query to ENS is a single call passing all the addresses of interest, so not much space for optimisation in that end (based on [the graph docs](https://thegraph.com/docs/en/subgraphs/querying/best-practices/#use-a-single-query-to-request-multiple-records …

Feat: increase function execution time

---

.github/workflows/build.yml
.github/workflows/chromatic.yml
apps/staking/next-env.d.ts
package.json
packages/ui/.gitignore
yarn.lock

Code changes to set the web app to run using the latest node runtime LTS (v22). No regressions were identified. 
> [!IMPORTANT]  
> For the reviewer/tester: It is important for sanity's sake to remove all the local node_modules before installation.
**For context:** I got caught up in a rabbit hole with a third-level dependency (@ensdomains/ens-contract) using an old version of hardhat that set the engine to maximum node v18. It led me to checkout [cartesi/staking-pool](https://github.com/cartesi/staking-pool) make upgrades, and install that locally into my staking project. That allowed the package manager to pass the engine checks and enabled the update in the `yarn.lock`, but it would cost a redeploy of contracts as there was a change in the imports of `ensdomains/ens-contracts` for a …

Upgrade runtime to latest LTS (22)

---

apps/staking/__tests__/hooks/useDebounce.test.ts
apps/staking/src/hooks/useDebounce.ts
apps/staking/src/pages/blocks/[[...block]].tsx
apps/staking/src/pages/stake/[pool]/users.tsx

I fixed the issue by disabling pagination for the `usePoolBalances` hook, when a search is being performed.
Additionally, I added debounce for the users' search to reduce the load on the server. Since similar logic is utilised on the `blocks` page as well I extracted the debounce logic into a custom hook and covered it with a unit test, and refactored both pages to use that hook.
Instructions can be found [here](https://github.com/cartesi/explorer/issues/185).

#185 Fix users search

---

apps/staking/__tests__/hooks/useDebounce.test.ts
apps/staking/jest.config.js
package.json
packages/ui/jest.config.js
packages/wallet/package.json
yarn.lock

Code changes to bump unleash sdk and proxy libs to its latest. Also, I removed a Jest setup for module-name-mapper related to `uuid` lib; it is not necessary anymore. I did an unrelated code change to a test case for the `useDebounce` tests. It was unstable as it was failing and passing from run to run (screenshot below). 
Changes: 
* Upgrade the Unleash sdk and proxy-client-react libs `explorer` and `packages/wallet`. 
* Remove unnecessary module-name-mapping for Jest configs `apps/staking` and `packages/ui`
* Update test case for `useDebounce` hook.
**ps: Tested on safe-global app.**
<details>
<summary><h3>Test failure message</h3></summary
</details>

Chore: Upgrade unleash sdk and proxy

---

.eslintrc
__tests__/services/server/AddressENSService.test.ts
__tests__/services/server/functions.test.ts
additional.d.ts
jest.setup.js
src/services/server/ens/AddressENSService.ts
src/services/server/ens/functions.ts
src/services/server/ens/types.ts

Code changes to handle a large number of entries to refresh and improve the decision when to or not to refresh entries depending on responses from important third-party (i.e. ENS Subgraph). 
_PS: Currently, the cronjob is turned off._ 
**Summary:**
- Added a new function to deal with refreshing existing data specifically. Located on `ens/functions.ts`, it will create partitions in case the number of items is bigger than a certain limit when querying ENS Subgraph service. 
- Added environment variable to set the limit of entries per request. The current default and maximum value is 900 items. It can be configured to be lower, but that defines the ratio between items/requests; the smaller the number of items, it will likely increase the number of concurrent requests to be sent. The …

Feat: improve behaviour to deal with stale entries (refreshEntries() service call)

---

CHANGELOG.md
package.json
src/pages/_app.tsx
yarn.lock

The previous form of collecting speed analytics for the web application was deprecated. Now it is only possible through that @vercel/speed-insights package.

feat: Add speed insights
